import { readFile } from "node:fs/promises";
import type { ImageProvider, LLMProvider, ProviderHealth, ProviderMetadata, RetryPolicy } from "./providers.js";
import { DEFAULT_RETRY_POLICY } from "./providers.js";
import { checkHttpHealth, withRetry } from "./provider-resilience.js";
import { mutateComfyUIWorkflow } from "./comfyui-workflow.js";
type OllamaConfig = { baseUrl:string; model:string; timeoutMs?:number; retry?:Partial<RetryPolicy> };
type OpenAIConfig = { baseUrl:string; model:string; timeoutMs?:number; apiKey?:string; retry?:Partial<RetryPolicy> };
type ComfyConfig = { baseUrl:string; workflow?:Record<string,unknown>; timeoutMs?:number; pollIntervalMs?:number; retry?:Partial<RetryPolicy> };
function timer(ms:number){const controller=new AbortController();const id=setTimeout(()=>controller.abort(),ms);return{signal:controller.signal,clear:()=>clearTimeout(id)};}
async function readJson(response:Response):Promise<any>{const text=await response.text();if(!response.ok)throw new Error("Provider HTTP "+response.status+": "+text.slice(0,500));return JSON.parse(text);}
function parseJson(text:string):unknown{const value=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");try{return JSON.parse(value);}catch{const start=value.indexOf("{"),end=value.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(value.slice(start,end+1));throw new Error("LLM returned invalid JSON.");}}
function retryPolicy(value?:Partial<RetryPolicy>):RetryPolicy{return{...DEFAULT_RETRY_POLICY,...value};}
export class OllamaLLMProvider implements LLMProvider{readonly metadata:ProviderMetadata;constructor(private readonly config:OllamaConfig){this.metadata={id:"ollama",name:"Ollama",model:config.model,local:true};}async health(){return checkHttpHealth({url:this.config.baseUrl.replace(/\/$/,"")+"/api/tags",timeoutMs:5000});}async generateStructured<T>(input:{prompt:string;schema:unknown}):Promise<T>{return withRetry(async()=>{const t=timer(this.config.timeoutMs??120000);try{const r=await fetch(this.config.baseUrl+"/api/chat",{method:"POST",signal:t.signal,headers:{"content-type":"application/json"},body:JSON.stringify({model:this.config.model,stream:false,format:input.schema,messages:[{role:"user",content:input.prompt}]})});const data=await readJson(r);return parseJson(data.message?.content??data.response) as T;}finally{t.clear();}},retryPolicy(this.config.retry));}}
export class OpenAICompatibleLLMProvider implements LLMProvider{readonly metadata:ProviderMetadata;constructor(private readonly config:OpenAIConfig){this.metadata={id:"openai-compatible",name:"OpenAI-compatible",model:config.model,local:true};}async health(){return checkHttpHealth({url:this.config.baseUrl.replace(/\/$/,"")+"/models",timeoutMs:5000});}async generateStructured<T>(input:{prompt:string;schema:unknown}):Promise<T>{return withRetry(async()=>{const t=timer(this.config.timeoutMs??120000);try{const headers:Record<string,string>={"content-type":"application/json"};if(this.config.apiKey)headers.authorization="Bearer "+this.config.apiKey;const r=await fetch(this.config.baseUrl+"/chat/completions",{method:"POST",signal:t.signal,headers,body:JSON.stringify({model:this.config.model,messages:[{role:"user",content:input.prompt}],response_format:{type:"json_schema",json_schema:{name:"openstory_output",strict:true,schema:input.schema}},temperature:.2})});const data=await readJson(r);return parseJson(data.choices?.[0]?.message?.content??"") as T;}finally{t.clear();}},retryPolicy(this.config.retry));}}
export class ComfyUIImageProvider implements ImageProvider{readonly metadata:ProviderMetadata={id:"comfyui",name:"ComfyUI",local:true};constructor(private readonly config:ComfyConfig){}async health(){return checkHttpHealth({url:this.config.baseUrl.replace(/\/$/,"")+"/system_stats",timeoutMs:5000});}
private async uploadReference(reference:string,signal:AbortSignal):Promise<string>{let bytes:Uint8Array;let filename="reference.png";if(/^https?:\/\//i.test(reference)){const r=await fetch(reference,{signal});if(!r.ok)throw new Error("Reference download failed: HTTP "+r.status);bytes=new Uint8Array(await r.arrayBuffer());}else{bytes=new Uint8Array(await readFile(reference.startsWith("file://")?new URL(reference):reference));filename=reference.split(/[\\\\/]/).pop()||filename;}const form=new FormData();form.append("image",new Blob([bytes]),filename);form.append("overwrite","true");form.append("type","input");const r=await fetch(this.config.baseUrl+"/upload/image",{method:"POST",signal,body:form});const data=await readJson(r);if(!data.name)throw new Error("ComfyUI reference upload returned no image name.");return data.subfolder?data.subfolder+"/"+data.name:data.name;}
async generate(input:{prompt:string;references?:string[];negativePrompt?:string;seed?:number;width?:number;height?:number;steps?:number;cfg?:number;sampler?:string;scheduler?:string;checkpoint?:string;ipAdapterWeight?:number}):Promise<{assetId:string;url:string}>{if(!this.config.workflow)throw new Error("ComfyUI workflow is required.");return withRetry(async()=>{const t=timer(this.config.timeoutMs??300000);try{const refs=input.references??[];const uploaded=refs.length?await this.uploadReference(refs[0]!,t.signal):undefined;const workflow=mutateComfyUIWorkflow(this.config.workflow,{prompt:input.prompt,negativePrompt:input.negativePrompt??"deformed, extra limbs, extra fingers, bad anatomy, duplicate character, mutated face, text, watermark, logo, blurry, low quality, cropped, out of frame, scary, gore, violence",seed:input.seed??Math.floor(Math.random()*2147483647),width:input.width??512,height:input.height??512,steps:input.steps??22,cfg:input.cfg??6.5,sampler:input.sampler??"dpmpp_2m",scheduler:input.scheduler??"karras",checkpoint:input.checkpoint,referenceImage:uploaded,ipAdapterWeight:input.ipAdapterWeight??.75});const submitted=await readJson(await fetch(this.config.baseUrl+"/prompt",{method:"POST",signal:t.signal,headers:{"content-type":"application/json"},body:JSON.stringify({prompt:workflow})}));if(!submitted.prompt_id)throw new Error("ComfyUI did not return prompt_id.");const deadline=Date.now()+(this.config.timeoutMs??300000);while(Date.now()<deadline){const history=await readJson(await fetch(this.config.baseUrl+"/history/"+submitted.prompt_id,{signal:t.signal}));for(const node of Object.values(history[submitted.prompt_id]?.outputs??{}) as any[]){const image=Array.isArray(node?.images)?node.images.find((x:any)=>x?.filename):undefined;if(image)return{assetId:submitted.prompt_id+":"+image.filename,url:this.config.baseUrl+"/view?filename="+encodeURIComponent(image.filename)+"&subfolder="+encodeURIComponent(image.subfolder??"")+"&type="+encodeURIComponent(image.type??"output")};}await new Promise(resolve=>setTimeout(resolve,this.config.pollIntervalMs??1000));}throw new Error("ComfyUI generation timed out.");}finally{t.clear();}},retryPolicy(this.config.retry));}}