import type { ComfyUIConfig, ImageProvider, LLMProvider, OllamaConfig, OpenAICompatibleConfig, ProviderMetadata } from "./providers.js";

type Extended<T> = T & { timeoutMs?: number; apiKey?: string; workflow?: Record<string, unknown>; pollIntervalMs?: number };
function timeoutSignal(ms: number) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), ms); return { signal: controller.signal, cleanup: () => clearTimeout(timer) }; }
async function readJson(response: Response): Promise<any> { const text = await response.text(); if (!response.ok) throw new Error(`Provider HTTP ${response.status}: ${text.slice(0, 500)}`); try { return JSON.parse(text); } catch { throw new Error(`Provider returned invalid JSON: ${text.slice(0, 500)}`); } }
function parseJson(text: string): unknown { const value = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, ""); try { return JSON.parse(value); } catch { const start = value.indexOf("{"); const end = value.lastIndexOf("}"); if (start >= 0 && end > start) return JSON.parse(value.slice(start, end + 1)); throw new Error("LLM returned invalid JSON."); } }

export class OllamaLLMProvider implements LLMProvider {
  readonly metadata: ProviderMetadata;
  constructor(private readonly config: OllamaConfig) { this.metadata = { id: "ollama", name: "Ollama", model: config.model, local: true }; }
  async generateStructured<T>(input: { prompt: string; schema: unknown }): Promise<T> { const config = this.config as Extended<OllamaConfig>; const t = timeoutSignal(config.timeoutMs ?? 120000); try { const response = await fetch(`${config.baseUrl}/api/chat`, { method: "POST", signal: t.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ model: config.model, stream: false, format: input.schema, messages: [{ role: "user", content: input.prompt }] }) }); const data = await readJson(response); return parseJson(data.message?.content ?? data.response) as T; } finally { t.cleanup(); } }
}

export class OpenAICompatibleLLMProvider implements LLMProvider {
  readonly metadata: ProviderMetadata;
  constructor(private readonly config: OpenAICompatibleConfig) { this.metadata = { id: "openai-compatible", name: "OpenAI-compatible", model: config.model, local: true }; }
  async generateStructured<T>(input: { prompt: string; schema: unknown }): Promise<T> { const config = this.config as Extended<OpenAICompatibleConfig>; const t = timeoutSignal(config.timeoutMs ?? 120000); try { const headers: Record<string, string> = { "content-type": "application/json" }; if (config.apiKey) headers.authorization = `Bearer ${config.apiKey}`; const response = await fetch(`${config.baseUrl}/chat/completions`, { method: "POST", signal: t.signal, headers, body: JSON.stringify({ model: config.model, messages: [{ role: "user", content: input.prompt }], response_format: { type: "json_schema", json_schema: { name: "openstory_output", strict: true, schema: input.schema } }, temperature: 0.2 }) }); const data = await readJson(response); return parseJson(data.choices?.[0]?.message?.content ?? "") as T; } finally { t.cleanup(); } }
}

export class ComfyUIImageProvider implements ImageProvider {
  readonly metadata: ProviderMetadata = { id: "comfyui", name: "ComfyUI", local: true };
  constructor(private readonly config: ComfyUIConfig) {}
  async generate(input: { prompt: string; references?: string[] }): Promise<{ assetId: string; url: string }> { const config = this.config as Extended<ComfyUIConfig>; if (!config.workflow) throw new Error("ComfyUI workflow is required."); const t = timeoutSignal(config.timeoutMs ?? 180000); try { const workflow = JSON.parse(JSON.stringify(config.workflow).replace(/\{\{PROMPT\}\}/g, input.prompt)); const submitted = await readJson(await fetch(`${config.baseUrl}/prompt`, { method: "POST", signal: t.signal, headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt: workflow }) })); if (!submitted.prompt_id) throw new Error("ComfyUI did not return prompt_id."); const deadline = Date.now() + (config.timeoutMs ?? 180000); while (Date.now() < deadline) { const history = await readJson(await fetch(`${config.baseUrl}/history/${submitted.prompt_id}`, { signal: t.signal })); const outputs = history[submitted.prompt_id]?.outputs; for (const node of Object.values(outputs ?? {}) as any[]) { const image = Array.isArray(node?.images) ? node.images.find((x: any) => x?.filename) : undefined; if (image) return { assetId: `${submitted.prompt_id}:${image.filename}`, url: `${config.baseUrl}/view?filename=${encodeURIComponent(image.filename)}&subfolder=${encodeURIComponent(image.subfolder ?? "")}&type=${encodeURIComponent(image.type ?? "output")}` }; } await new Promise(resolve => setTimeout(resolve, config.pollIntervalMs ?? 1000)); } throw new Error("ComfyUI generation timed out."); } finally { t.cleanup(); } }
}
